apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nombremicroservicio
  name: nombremicroservicio-deployment
  namespace: nombredominio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nombremicroservicio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nombremicroservicio
    spec:
      containers:
        - name: nombremicroservicio
          image: bancopichinchaec.azurecr.io/bp/nombredominio/nombremicroservicio:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: 
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "200m"

---
kind: Service
apiVersion: v1
metadata:
  name: nombremicroservicio-service
  namespace: nombredominio
  labels:
    app: nombremicroservicio
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nombremicroservicio
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nombremicroservicio-autoscaling
  namespace: nombredominio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nombremicroservicio-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
